Adds lvm2 package to prevent vgscan missing error
Lists lvm2 package as a Rescuezilla dependency as on an unmodified Debian 11
system produced the following error: [1]

FileNotFoundError: [Errno 2] No such file or directory: 'vgscan'

[1] https://sourceforge.net/p/rescuezilla/discussion/support/thread/77a02f67e1/